UPDATE R5INVOICELINES
SET IVL_INVVALUE = ROUND(IVL_INVVALUE, 2),
	IVL_DISCOUNT = ROUND(IVL_DISCOUNT, 2),
	IVL_PRICE = ROUND(IVL_PRICE, 2),
	IVL_TOTTAXAMOUNT = ROUND(IVL_TOTTAXAMOUNT, 2),
	IVL_TOTEXTRA = ROUND(IVL_TOTEXTRA, 2)
WHERE IVL_SQLIDENTITY = :rowid
	AND (
		IVL_AMOUNT <> ROUND(IVL_AMOUNT, 2)
		OR IVL_TAXAMOUNT <> ROUND(IVL_TAXAMOUNT, 2)
	)


