UPDATE R5INVDISTRIBUTIONS
SET IVD_TAXAMOUNT = ROUND(IVD_TAXAMOUNT, 2),
	IVD_AMOUNT = ROUND(IVD_AMOUNT, 2)
WHERE IVD_SQLIDENTITY = :rowid
	AND (
		IVD_AMOUNT <> ROUND(IVD_AMOUNT, 2)
		OR IVD_TAXAMOUNT <> ROUND(IVD_TAXAMOUNT, 2)
	)