
RQL_RSTATUS = 'A'
RQL_RTYPE = 'S%'

RQL_EVENT = WorkOrder
RQL_ACT = Activity

ACT_UDFCHAR02 = (SELECT RQL_PRICE * RQL_QTY * RQL_EXCH FROM R5REQUISLINES WHERE RQL_RSTATUS = 'A' AND RQL_RTYPE = 'S%' AND RQL_EVENT = ACT_EVENT AND RQL_ACT = ACT_ACT)



SELECT ACT_EVENT,
ACT_ACT,
CASE WHEN ACT_HIRE = '+' 
THEN (RQL_PRICE * RQL_QTY * RQL_EXCH) 
ELSE (ACT_REM * TRR_NTRATE) END as Lab
                        
FROM R5ACTIVITIES 
LEFT OUTER JOIN R5REQUISLINES ON RQL_EVENT = ACT_EVENT 
AND RQL_ACT = ACT_ACT
LEFT OUTER JOIN R5TRADERATES ON ACT_TRADE = TRR_TRADE
WHERE RQL_RSTATUS = 'A' AND RQL_RTYPE LIKE 'S_'

SELECT ACT_EVENT,
ACT_ACT,
CASE WHEN ACT_HIRE = '+' 
THEN SUM(RQL_PRICE * RQL_QTY * RQL_EXCH) 
ELSE SUM(dbo.o7plnqty(trl_event,trl_act,trl_part,trl_part_org,trl_store,trl_line)*PPR_AVGPRICE) END as Mat
                        
FROM R5ACTIVITIES 
LEFT OUTER JOIN R5REQUISLINES ON RQL_EVENT = ACT_EVENT AND RQL_ACT = ACT_ACT
LEFT OUTER JOIN R5TRANSLINES ON TRL_EVENT = ACT_EVENT AND TRL_ACT = ACT_ACT
LEFT OUTER JOIN R5PARTPRICES ON PPR_PART = TRL_PART

WHERE RQL_RSTATUS = 'A' AND RQL_RTYPE LIKE 'P_'

GROUP BY ACT_EVENT,
ACT_ACT