SELECT
EVT_CODE,
DBO.REPHOURS(EVT_CODE) HOURS,
DBO.REPLABOUR(EVT_CODE) LABOR_COST,
DBO.REPMATERIAL(EVT_CODE) MATERIAL_COST,
(DBO.REPMATERIAL(EVT_CODE) + DBO.REPLABOUR(EVT_CODE)) TOTAL_COST
FROM R5EVENTS
WHERE
EVT_TYPE IN ('JOB','PPM')