SELECT EVT_MRC,
       EVT_STATUS,
/*       PLAN_UNPLAN,*/
       EVT_JOBTYPE,
       COUNT(EVT_CODE) CNT_WO
FROM       
(		SELECT CASE WHEN EVT_MRC IN ('ENG','*') THEN 'ENG' ELSE EVT_MRC END EVT_MRC,
			   CASE WHEN EVT_STATUS IN ('C','CLOS') THEN 'Completed'
					/*Check that it is a child in PLAN status, but the parent is C status*/
					WHEN EVT_STATUS = 'PLAN' AND EXISTS (SELECT 1 FROM R5EVENTS E2 WHERE E1.EVT_PARENT = E2.EVT_CODE AND E2.EVT_STATUS IN ('C','CLOS')) THEN 'Completed'
WHEN (SELECT SUM(BOO_HOURS) FROM R5BOOKEDHOURS INNER JOIN R5EVENTS E2 ON BOO_EVENT=E2.EVT_CODE  WHERE BOO_EVENT=E1.EVT_CODE OR E2.EVT_PARENT=E1.EVT_CODE)>0 THEN 'Completed'
					ELSE 'In Progress' END EVT_STATUS,
		/*       CASE WHEN EVT_UDFCHKBOX02='+' THEN 'Unscheduled' ELSE 'Scheduled'END PLAN_UNPLAN,*/
			   CASE WHEN E1.EVT_JOBTYPE IN ('PMIN','PMCA','PMCM','PMSV','PMOH','MEC') THEN 'Preventative'
					WHEN E1.EVT_JOBTYPE IN ('CMPR','CMEM','CMBD') THEN 'Corrective'
					WHEN E1.EVT_JOBTYPE IN ('PMRP') THEN 'Replacement'
					WHEN E1.EVT_JOBTYPE IN ('EMPM') THEN 'Improvement'
					ELSE 'Other' END EVT_JOBTYPE,
			   EVT_CODE                    
		FROM R5EVENTS E1
		WHERE E1.EVT_RTYPE IN ('PPM','JOB')
		AND E1.EVT_MRC IN ('ENG','*')
		AND E1.EVT_JOBTYPE  IN  ('PMIN','PMCA','PMCM','PMSV','PMOH','CMPR','CMEM','CMBD','PMRP','EMPM','MEC')
		AND E1.EVT_STATUS <> 'CANC' 
		AND ( /*Get WOs that are scheduled in the period, or their parent WO is scheduled in the period*/
				(EVT_CODE IN (SELECT ACS_EVENT FROM R5ACTSCHEDULES WHERE CONVERT(VARCHAR(10),ACS_SCHED,120) BETWEEN #prompt('SEL_START')# AND #prompt('SEL_END')#))
			OR	(EVT_PARENT in (SELECT ACS_EVENT FROM R5ACTSCHEDULES WHERE CONVERT(VARCHAR(10),ACS_SCHED,120) BETWEEN #prompt('SEL_START')# AND #prompt('SEL_END')#))
			)
) temp
	GROUP BY EVT_MRC, EVT_STATUS, EVT_JOBTYPE