SELECT EVT_CODE, EVT_DESC,
               SUM(ACT_EST) EVT_ESTHOURS,   
               SUM(ACT_REM)/SUM(ACT_EST) EVT_PERC,
               EVT_TARGET,EVT_SCHEDEND,
               EVT_SCHEDGRP ECT_OWNER, EVT_OBJECT,
               EVT_MRC, EVT_STATUS, EVT_LOCATION
               
FROM R5EVENTS
LEFT OUTER JOIN R5ACTIVITIES ON EVT_CODE = ACT_EVENT
WHERE EVT_RSTATUS NOT IN ('C','A')
AND EVT_STATUS NOT IN ('CLOS','CANC')
AND(EVT_JOBTYPE NOT IN ('MEC','SYSUPD','AMPACT','NMST','NMTR'))
AND EVT_PPM IS NOT NULL
GROUP BY       EVT_SCHEDEND, EVT_SCHEDGRP, EVT_OBJECT, EVT_MRC, EVT_STATUS, EVT_LOCATION, EVT_CODE, EVT_UDFCHKBOX04, EVT_UDFCHKBOX03, EVT_UDFCHAR15, EVT_TARGET, EVT_DESC


ROLLUP for a start for the aggregation

SELECT EVT_CODE, EVT_DESC,
               SUM(ACT_EST) EVT_ESTHOURS,   
               SUM(ACT_REM)/SUM(ACT_EST) EVT_PERC,
               EVT_TARGET,EVT_SCHEDEND,
               EVT_SCHEDGRP EVT_OWNER, EVT_OBJECT,
               EVT_MRC, EVT_STATUS, EVT_LOCATION, 3 AS ID_GROUP
               
FROM R5EVENTS
LEFT OUTER JOIN R5ACTIVITIES ON EVT_CODE = ACT_EVENT
WHERE EVT_RSTATUS NOT IN ('C','A')
AND EVT_STATUS NOT IN ('CLOS','CANC')
AND(EVT_JOBTYPE NOT IN ('MEC','SYSUPD','AMPACT','NMST','NMTR'))
AND EVT_PPM IS NOT NULL
GROUP BY EVT_DESC,  EVT_SCHEDEND, EVT_SCHEDGRP, EVT_OBJECT, EVT_MRC, EVT_STATUS, EVT_LOCATION, EVT_CODE, EVT_UDFCHKBOX04, EVT_UDFCHKBOX03, EVT_UDFCHAR15, EVT_TARGET
UNION ALL
SELECT MAX(EVT_CODE) CODE, EVT_DESC,
               SUM(ACT_EST) EVT_ESTHOURS,   
               SUM(ACT_REM)/SUM(ACT_EST) EVT_PERC,
               MIN(EVT_TARGET),MAX(EVT_SCHEDEND),
               EVT_SCHEDGRP EVT_OWNER, EVT_OBJECT,
               EVT_MRC, EVT_STATUS, EVT_LOCATION, 2 AS ID_GROUP
               
FROM R5EVENTS
LEFT OUTER JOIN R5ACTIVITIES ON EVT_CODE = ACT_EVENT
WHERE EVT_RSTATUS NOT IN ('C','A')
AND EVT_STATUS NOT IN ('CLOS','CANC')
AND(EVT_JOBTYPE NOT IN ('MEC','SYSUPD','AMPACT','NMST','NMTR'))
AND EVT_PPM IS NOT NULL
GROUP BY GROUPING SETS ((EVT_DESC,EVT_MRC,EVT_STATUS,EVT_LOCATION))
ORDER BY EVT_DESC
