SELECT WorkOrder,
MAX(Description) as Description,
SUM(Total) as Total,
CostCode,
BudgetClass,
Strategy,
Rtype,
Type
FROM (SELECT
ISNULL(EVT_PARENT,BOO_EVENT) AS WorkOrder,
EVT_DESC as Description,
BOO_COST AS Total,
EVT_COSTCODE AS CostCode,
(SELECT OBJ_UDFCHAR34 FROM R5OBJECTS WHERE OBJ_CODE = EVT_OBJECT) AS BudgetClass,
(SELECT OBJ_UDFCHAR39 FROM R5OBJECTS WHERE OBJ_CODE = EVT_OBJECT) AS Strategy,
'Labour' AS RType, 
'IL' AS Type
FROM R5BOOKEDHOURS
LEFT OUTER JOIN R5EVENTS ON EVT_CODE = BOO_EVENT 
WHERE BOO_PERSON IS NOT NULL AND DATEPART(month, BOO_ENTERED) = #prompt('Month')# AND DATEPART(year, BOO_ENTERED) = #prompt('Year')#
UNION ALL
SELECT ISNULL(EVT_PARENT,BOO_EVENT) AS WorkOrder,
EVT_DESC as Description,
BOO_COST AS Total,
EVT_COSTCODE AS CostCode,
(SELECT OBJ_UDFCHAR34 FROM R5OBJECTS WHERE OBJ_CODE = EVT_OBJECT) AS BudgetClass,
(SELECT OBJ_UDFCHAR39 FROM R5OBJECTS WHERE OBJ_CODE = EVT_OBJECT) AS Strategy,
'Labour' AS RType, 
'HL' AS Type
FROM R5BOOKEDHOURS
LEFT OUTER JOIN R5EVENTS on BOO_EVENT = EVT_CODE
LEFT OUTER JOIN R5ORDERLINES ON CASE WHEN EVT_ROUTEPARENT IS NULL THEN BOO_EVENT ELSE EVT_PARENT  END = ORL_EVENT AND BOO_ACT = ORL_ACT AND ORL_PART IS NULL 
WHERE BOO_PERSON IS NULL AND BOO_ORDER IS NULL AND BOO_COST <> 0 AND DATEPART(month, BOO_ENTERED) = #prompt('Month')# AND DATEPART(year, BOO_ENTERED) = #prompt('Year')#

UNION ALL
SELECT ISNULL(EVT_PARENT,BOO_EVENT) AS WorkOrder,
EVT_DESC as Description,
BOO_COST AS Total,
ORL_COSTCODE AS CostCode,
(SELECT OBJ_UDFCHAR34 FROM R5OBJECTS WHERE OBJ_CODE = EVT_OBJECT) AS BudgetClass,
(SELECT OBJ_UDFCHAR39 FROM R5OBJECTS WHERE OBJ_CODE = EVT_OBJECT) AS Strategy,
'Labour' AS RType, 
'HL' AS Type
FROM R5BOOKEDHOURS
LEFT OUTER JOIN R5EVENTS ON BOO_EVENT = EVT_CODE
LEFT OUTER JOIN R5ORDERLINES ON BOO_ORDER = ORL_ORDER AND BOO_ORDLINE = ORL_ORDLINE AND ORL_PART IS NULL 
WHERE BOO_PERSON IS NULL AND BOO_ORDER IS NOT NULL AND DATEPART(month, BOO_ENTERED) = #prompt('Month')# AND DATEPART(year, BOO_ENTERED) = #prompt('Year')#
UNION ALL
SELECT
ISNULL(EVT_PARENT,TRL_EVENT) AS WorkOrder,
EVT_DESC as Description,
CASE WHEN TRL_RTYPE = 'RECV' THEN TRL_QTY*TRL_PRICE
           WHEN TRL_RTYPE = 'RETN' THEN TRL_QTY*-1*TRL_PRICE
           ELSE 0 END AS Total,
ORL_COSTCODE AS CostCode,
(SELECT OBJ_UDFCHAR34 FROM R5OBJECTS WHERE OBJ_CODE = EVT_OBJECT) AS BudgetClass,
(SELECT OBJ_UDFCHAR39 FROM R5OBJECTS WHERE OBJ_CODE = EVT_OBJECT) AS Strategy,
'Part' AS RType, 
'DI' AS Type
FROM R5TRANSLINES
LEFT OUTER JOIN R5EVENTS on TRL_EVENT = EVT_CODE
LEFT OUTER JOIN R5ORDERLINES ON TRL_ORDER = ORL_ORDER AND TRL_ORDLINE = ORL_ORDLINE
WHERE TRL_IO = 0 AND TRL_RTYPE IN ('RECV','RETN') AND DATEPART(month, TRL_DATE) = #prompt('Month')# AND DATEPART(year, TRL_DATE) = #prompt('Year')#
UNION ALL
SELECT
ISNULL(EVT_PARENT,TRL_EVENT) AS WorkOrder,
EVT_DESC as Description,
TRL_PRICE*TRL_QTY AS Total,
TRL_COSTCODE AS CostCode,
(SELECT OBJ_UDFCHAR34 FROM R5OBJECTS WHERE OBJ_CODE = EVT_OBJECT) AS BudgetClass,
(SELECT OBJ_UDFCHAR39 FROM R5OBJECTS WHERE OBJ_CODE = EVT_OBJECT) AS Strategy,
'Part' AS RType, 
'ST' AS Type
FROM R5TRANSLINES st
LEFT OUTER JOIN R5EVENTS on TRL_EVENT = EVT_CODE
LEFT OUTER JOIN R5ORDERLINES ON TRL_ORDER = ORL_ORDER AND TRL_ORDLINE = ORL_ORDLINE 
WHERE TRL_EVENT IS NOT NULL AND TRL_RTYPE = 'I' AND TRL_IO = -1 AND DATEPART(month, TRL_DATE) = #prompt('Month')# AND DATEPART(year, TRL_DATE) = #prompt('Year')#
) as A
GROUP BY WorkOrder,CostCode,BudgetClass,Strategy,Rtype,Type
ORDER BY WorkOrder,Type,CostCode
