DECLARE
  @docId   nvarchar(80),
 @ent nvarchar(8),
  @whereused   nvarchar(100);
BEGIN
SELECT 
@docId = DOC_CODE
,@whereused = DOC_UDFCHAR01
,@ent = DOC_UDFCHAR02
FROM R5DOCUMENTS 
WHERE DOC_SQLIDENTITY = :rowid AND DOC_UDFCHAR01 IS NOT NULL

IF @whereused IS NOT NULL
BEGIN
INSERT INTO R5DOCENTITIES(DAE_DOCUMENT,DAE_ENTITY,DAE_RENTITY,DAE_TYPE,DAE_RTYPE,DAE_CODE,DAE_COPYTOWO,DAE_PRINTONWO,DAE_COPYTOPO,DAE_PRINTONPO)
VALUES( @docId,@ent,@ent,'*','*',@whereused,'-','-','-','-')
END
END
