SELECT
	EVT_CODE,
	EVT_DESC,
	DBO.REPGETDESC('EN','UCOD',EVT_JOBTYPE,'JBTP',NULL) EVT_JOBTYPE_DESC,
	EVT_STATUS,
	DBO.REPGETDESC('EN','UCOD',EVT_STATUS,'EVST',NULL) EVT_STATUS_DESC,
	EVT_OBJECT,
	EVT_REQUESTEND,
	EVT_SCHEDGRP,
	EVT_UDFCHAR11,
	EVT_UDFDATE02,
	EVT_PRIORITY,
	EVT_PARENT,
	EVT_JOBTYPE


FROM R5EVENTS
AND (EVT_JOBTYPE IN ('EMIN') OR EVT_JOBTYPE IN ('EMTM') OR EVT_JOBTYPE IN ('EMPM'))
AND EVT_STATUS_DESC IN ('In Progress','Scheduling')