SELECT  ORL_ORDER,
        ORL_ORDLINE,
        ORL_PART,
	ORL_SUPPLIER,
	ORL_ACTIVE,
	ORL_RECVVALUE,
	ORL_EVENT,
	ORL_STATUS,
	ORL_COSTCODE,
	ORL_UDFCHAR07,
	ORL_UDFCHAR09,
	ORL_DUE,
	ORL_PURUOM,
        ORL_ORDQTY SUMORL_ORDQTY,
	ORL_PRICE SUMORL_PRICE,
	ORL_ORDQTY*ORL_PRICE*(1/ORL_EXCH) EXTD_PRICE,
	DBO.REPGETDESC('EN','PART',ORL_PART,NULL,NULL) ORL_PART_DESC,
       		CASE WHEN ORL_TYPE LIKE 'S%' 
           		THEN DBO.REPGETADDTEXT('EVNT','EN',ORL_EVENT+'#'+ CAST(ORL_ACT AS NVARCHAR(10)))   
		ELSE DBO.REPGETADDTEXT('PORL','EN',ORL_ORDER+'#'+ORL_ORDER_ORG+'#'+CAST(ORL_ORDLINE AS NVARCHAR(10))) END  POLINE_COMMENTS,
	CASE [ORD_STATUS]
		WHEN 'A' THEN 'Approved'
		WHEN 'AR' THEN 'Fully Received'
		WHEN 'PR' THEN 'Partially Received'
		WHEN 'U' THEN 'Unfinished'
		ELSE 'error'
		END ORDER_STATUS,
	CASE WHEN ORL_ACTIVE ='+' THEN 'Y' ELSE 'N' END ACTIVE,
	CASE WHEN ORL_RECVVALUE IS NULL THEN '0' ELSE ORL_RECVVALUE*(1/ORL_EXCH) END RECEIVED,
	(ORL_ORDQTY*ORL_PRICE*(1/ORL_EXCH)) - (CASE WHEN ORL_RECVVALUE IS NULL THEN '0' ELSE ORL_RECVVALUE*(1/ORL_EXCH) END) COMMITTED,
	CASE WHEN ORD_UDFCHKBOX01 = '+' THEN 'Yes' ELSE 'No' END FINANCIAL_CLOSE,
	CST_DESC,
	CASE WHEN (DBO.REPGETDESC('EN','PART',ORL_PART,NULL,NULL)) IS NULL 
		THEN 	(CASE WHEN ORL_TYPE LIKE 'S%' 
		THEN DBO.REPGETADDTEXT('EVNT','EN',ORL_EVENT+'#'+ CAST(ORL_ACT AS NVARCHAR(10))) 
		ELSE DBO.REPGETADDTEXT('PORL','EN',ORL_ORDER+'#'+ORL_ORDER_ORG+'#'+CAST(ORL_ORDLINE AS NVARCHAR(10))) END) 
		ELSE (DBO.REPGETDESC('EN','PART',ORL_PART,NULL,NULL)) END LINE_COMMENT,
       	CAT_REF,
	ORD_DESC,
	ORD_APPROV,
	ORD_DATE,
	ORD_STATUS,
	ORD_UDFCHKBOX01,
	EVT_DESC,
       	REQ_AUTH,
	DBO.REPGETDESC ('EN','COMP',[ORL_SUPPLIER],NULL,NULL) SUPPLIER_DESC,
	ORD_ORIGIN,
	ORL_REQ,
	REQ_DATEAPPROVED,
	REQ_DATE,
	ORD_DUE,
        SUM(RT.BOO_COST) Service,
       CASE WHEN SUM(RT.BOO_COST) = 0 THEN SUM(RT.BOO_RATE*RT.BOO_ORIGHOURS) ELSE SUM(RT.BOO_COST) END ServiceMain,
        SUM(RT.BOO_RATE*RT.BOO_ORIGHOURS) Service2,
        SUM(TT.TRL_PRICE*TT.TRL_QTY) Parts,
      CASE WHEN(CASE WHEN SUM(RT.BOO_COST) = 0 THEN SUM(RT.BOO_RATE*RT.BOO_ORIGHOURS) ELSE SUM(RT.BOO_COST) END) IS NULL THEN '0' ELSE (CASE WHEN SUM(RT.BOO_COST) = 0 THEN SUM(RT.BOO_RATE*RT.BOO_ORIGHOURS) ELSE SUM(RT.BOO_COST) END) END + CASE WHEN (SUM(TT.TRL_PRICE*TT.TRL_QTY)) IS NULL THEN '0' ELSE  SUM(TT.TRL_PRICE*TT.TRL_QTY) END Receipted,
      CASE WHEN(CASE WHEN SUM(RF.BOO_COST) = 0 THEN SUM(RF.BOO_RATE*RF.BOO_ORIGHOURS) ELSE SUM(RF.BOO_COST) END) IS NULL THEN '0' ELSE (CASE WHEN SUM(RF.BOO_COST) = 0 THEN SUM(RF.BOO_RATE*RF.BOO_ORIGHOURS) ELSE SUM(RF.BOO_COST) END) END + CASE WHEN (SUM(TF.TRL_PRICE*TF.TRL_QTY)) IS NULL THEN '0' ELSE  SUM(TF.TRL_PRICE*TF.TRL_QTY) END Receipted_Filter
       
FROM R5ORDERLINES
LEFT OUTER JOIN R5ORDERS ON ORL_ORDER = ORD_CODE
LEFT OUTER JOIN R5COSTCODES ON ORL_COSTCODE = CST_CODE
LEFT OUTER JOIN R5REQUISITIONS ON ORL_REQ = REQ_CODE
LEFT OUTER JOIN R5EVENTS ON ORL_EVENT = EVT_CODE
LEFT OUTER JOIN R5CATALOGUE ON ORL_PART=CAT_PART AND ORL_PART_ORG=CAT_PART_ORG AND ORL_SUPPLIER=CAT_SUPPLIER AND ORL_SUPPLIER_ORG=CAT_SUPPLIER_ORG
LEFT OUTER JOIN R5TRANSLINES AS  TT ON ORL_ORDER = TT.TRL_ORDER AND ORL_ORDLINE = TT.TRL_ORDLINE AND TT.TRL_TYPE NOT LIKE 'RETN' AND TT.TRL_TYPE NOT LIKE 'I' 

LEFT OUTER JOIN R5BOOKEDHOURS AS RT ON ((ORL_TYPE = 'ST' OR ORL_TYPE = 'SF') AND RT.BOO_EVENT = ORL_EVENT AND RT.BOO_ACT = ORL_ACT) OR (ORL_TYPE = 'SH' AND RT.BOO_ORDER = ORL_ORDER AND RT.BOO_ORDLINE = ORL_ORDLINE)  

LEFT OUTER JOIN R5TRANSLINES AS  TF ON ORL_ORDER = TF.TRL_ORDER AND ORL_ORDLINE = TF.TRL_ORDLINE AND TF.TRL_TYPE NOT LIKE 'RETN' AND TF.TRL_TYPE NOT LIKE 'I' AND TF.TRL_UPDATED >= #prompt('START_DATER')# AND TF.TRL_UPDATED <= #prompt('END_DATER')#

LEFT OUTER JOIN R5BOOKEDHOURS AS  RF ON ((ORL_TYPE = 'ST' OR ORL_TYPE = 'SF') AND RF.BOO_EVENT = ORL_EVENT AND RF.BOO_ACT = ORL_ACT AND RF.BOO_ENTERED >= #prompt('START_DATER')# AND RF.BOO_ENTERED <= #prompt('END_DATER')#) OR (ORL_TYPE = 'SH' AND RF.BOO_ORDER = ORL_ORDER AND RF.BOO_ORDLINE = ORL_ORDLINE AND RF.BOO_ENTERED >= #prompt('START_DATER')# AND RF.BOO_ENTERED <= #prompt('END_DATER')#) 

WHERE ORL_STATUS = 'A'
AND ORD_STATUS NOT LIKE 'C'
AND ORD_UDFCHKBOX01 = '-'
AND ORD_DATE >= #prompt('START_DATE')#
AND ORD_DATE <= #prompt('END_DATE')#
AND ORD_STATUS IN (#promptmany('ORDER_STAT')#)
AND CASE WHEN ORD_UDFCHKBOX01 = '+' THEN 'Yes' ELSE 'No' END IN (#promptmany('FIN_CLOS')#)
AND CASE WHEN (DBO.REPGETDESC('EN','PART',ORL_PART,NULL,NULL)) IS NULL THEN 'S' ELSE 'P' END IN (#promptmany('PART_SERV')#)
GROUP BY ORL_ORDER,ORL_ORDLINE,ORL_PART,ORL_SUPPLIER,ORL_ACTIVE,ORL_RECVVALUE,ORL_EVENT,ORL_STATUS,ORL_COSTCODE,ORL_UDFCHAR07,ORL_UDFCHAR09,ORL_DUE,ORL_PURUOM,ORL_ORDQTY,ORL_PRICE,CST_DESC,CAT_REF,ORD_DESC,ORD_APPROV,ORD_DATE,ORD_STATUS,ORD_UDFCHKBOX01,EVT_DESC,REQ_AUTH,ORD_ORIGIN,ORL_REQ,REQ_DATEAPPROVED,REQ_DATE,ORD_DUE,ORL_ORDER_ORG,ORL_ACT,ORL_TYPE,TT.TRL_PRICE,ORL_EXCH,TF.TRL_PRICE
 