DECLARE
DECLARE
@wo nvarchar(30)
,@object nvarchar(30)
,@type nvarchar(5)
,@ppm nvarchar(30)
,@ppopk nvarchar(30);


SET @wo =  '10923093'
,@object = ''

BEGIN
    DELETE FROM R5EVENTOBJECTS WHERE EOB_EVENT = @wo
END
BEGIN
    UPDATE R5EVENTS
    SET
    EVT_RTYPE = 'JOB'
    ,EVT_PPM = NULL
    ,EVT_PPOPK = NULL
    WHERE EVT_CODE = @wo
    UPDATE R5EVENTS
    SET
    EVT_RTYPE = 'JOB'
    ,EVT_OBJECT = @object
    WHERE EVT_CODE = @wo

 END

INSERT INTO R5EVENTOBJECTS(EOB_EVENT,EOB_OBTYPE,EOB_OBRTYPE,EOB_OBJECT,EOB_LEVEL,EOB_ROLLUP,EOB_DOWNTIME,EOB_OBJECT_ORG)
VALUES(@wo,'P','P',@object,'0','+','+','VDP')
    INSERT INTO R5EVENTOBJECTS(EOB_EVENT,EOB_OBTYPE,EOB_OBRTYPE,EOB_OBJECT,EOB_LEVEL,EOB_ROLLUP,EOB_DOWNTIME,EOB_OBJECT_ORG)
    VALUES(@wo,'S','S','SYS-30.01.01.03','1','+','+','VDP')
    INSERT INTO R5EVENTOBJECTS(EOB_EVENT,EOB_OBTYPE,EOB_OBRTYPE,EOB_OBJECT,EOB_LEVEL,EOB_ROLLUP,EOB_DOWNTIME,EOB_OBJECT_ORG)
    VALUES(@wo,'S','S','SYS-30.01.01','2','+','+','VDP')
    INSERT INTO R5EVENTOBJECTS(EOB_EVENT,EOB_OBTYPE,EOB_OBRTYPE,EOB_OBJECT,EOB_LEVEL,EOB_ROLLUP,EOB_DOWNTIME,EOB_OBJECT_ORG)
    VALUES(@wo,'S','S','SYS-30.01','3','+','+','VDP')
    INSERT INTO R5EVENTOBJECTS(EOB_EVENT,EOB_OBTYPE,EOB_OBRTYPE,EOB_OBJECT,EOB_LEVEL,EOB_ROLLUP,EOB_DOWNTIME,EOB_OBJECT_ORG)
    VALUES(@wo,'S','S','SYS-30','4','+','+','VDP')
    INSERT INTO R5EVENTOBJECTS(EOB_EVENT,EOB_OBTYPE,EOB_OBRTYPE,EOB_OBJECT,EOB_LEVEL,EOB_ROLLUP,EOB_DOWNTIME,EOB_OBJECT_ORG)
    VALUES(@wo,'S','S','DESALVIC','5','+','+','VDP')
