DECLARE
@orlMRC NVARCHAR(40),
@evtMRC NVARCHAR(40);

BEGIN
	SELECT
		@orlMRC = ORL_UDFCHAR07,
		@evtMRC	= EVT_MRC
	FROM R5BOOKEDHOURS
	LEFT OUTER JOIN R5EVENTS ON BOO_EVENT = EVT_CODE
	LEFT OUTER JOIN R5ORDERLINES ON BOO_ORDER = ORL_ORDER 
								AND BOO_ORDLINE = ORL_ORDLINE
	WHERE boo_sqlidentity = :rowid 
		AND BOO_PERSON IS NULL 
		AND BOO_ORDER IS NOT NULL

	IF @orlMRC IS NOT NULL AND @orlMRC <> @evtMRC
		BEGIN
			RAISERROR( 'You cannot book contractor hours to a WO of a different Cost Centre than the PO', 16 , 1)
		END

END

