DELETE FROM R5GLCODECOMBINATIONS
WHERE RIGHT('0000'+ CONVERT(VARCHAR,GLC_SEGMENT1),4) IN (
        SELECT CST_CODE
        FROM R5COSTCODES
        WHERE CST_NOTUSED = '+'
            AND CST_SQLIDENTITY = :rowid
    )

UPDATE R5GLCODECOMBINATIONS
SET GLC_DESCRIPTION = CST_CODE + ' - ' + CST_DESC
FROM R5GLCODECOMBINATIONS
    LEFT OUTER JOIN R5COSTCODES ON RIGHT('0000'+ CONVERT(VARCHAR,GLC_SEGMENT1),4) = CST_CODE
WHERE CST_SQLIDENTITY = :rowid

INSERT INTO R5GLCODECOMBINATIONS (
        GLC_CODECOMBINATIONID,
        GLC_DETAILPOSTINGALLOWEDFLAG,
        GLC_ACCOUNTTYPE,
        GLC_ENABLEDFLAG,
        GLC_SEGMENT1,
        GLC_DESCRIPTION,
        GLC_LASTUPDATEDATE,
        GLC_LASTUPDATEDBY,
        GLC_CHARTOFACCOUNTSID,
        GLC_DETAILBUDGETINGALLOWEDFLAG,
        GLC_SUMMARYFLAG,
        glc_startdateactive,
        glc_enddateactive
    )
SELECT CST_CODE,
    'Y',
    'L',
    'Y',
    CST_CODE,
    CST_CODE + ' - ' + CST_DESC,
    GETDATE(),
    0,
    1,
    'N',
    'N',
    '01-JAN-2020',
    '01-JAN-2030'
FROM R5COSTCODES
WHERE CST_CODE NOT IN (
        SELECT RIGHT('0000'+ CONVERT(VARCHAR,GLC_SEGMENT1),4)
        FROM R5GLCODECOMBINATIONS
    )
    AND CST_NOTUSED = '-'
    AND CST_SQLIDENTITY = :rowid
