DECLARE 
@i NVARCHAR(100),
@v_id   integer,
@user nvarchar(80);

EXECUTE @v_id = O7SESS_CUR_USER @user OUTPUT;


BEGIN
	SELECT 	@i = COUNT(IVL_SQLIDENTITY)
	FROM  r5invoices
	LEFT OUTER JOIN R5INVOICELINES ON IVL_INVOICE = INV_CODE
	WHERE inv_status <> 'U'
	AND IVL_TAX IS NULL
	AND inv_sqlidentity = :ROWID;

	SELECT 	@i = @I + COUNT(IVD_SQLIDENTITY)
	FROM  r5invoices
	LEFT OUTER JOIN r5invdistributions ON IVD_INVOICE = INV_CODE
	WHERE inv_status <> 'U'
	AND IVD_TAX IS NULL
	AND inv_sqlidentity = :ROWID;


	IF @i > 0
	BEGIN
		RAISERROR('Tax Code is missing from 1 or more lines',16,1);
	END

END

BEGIN
UPDATE R5INVOICES
SET INV_UDFCHKBOX01 = '-'
,INV_STATUS = 'U'
,INV_RSTATUS = 'U'
WHERE INV_SQLIDENTITY = :rowid AND INV_UDFCHKBOX01 = '+' AND INV_STATUS = 'A' AND INV_TYPE = 'N' AND @user = 'ALEACH'
END

BEGIN
UPDATE R5INVOICES
SET INV_UDFCHKBOX01 = '-'
,INV_STATUS = 'U'
,INV_RSTATUS = 'U'
WHERE INV_SQLIDENTITY = :rowid AND INV_UDFCHKBOX01 = '+' AND INV_STATUS = 'A' AND INV_TYPE = 'I' AND @user = 'ALEACH'
END

BEGIN
UPDATE R5INVOICES
SET INV_UDFCHKBOX01 = '-'
,INV_STATUS = 'A'
,INV_RSTATUS = 'A'
WHERE INV_SQLIDENTITY = :rowid AND INV_UDFCHKBOX01 = '+' AND INV_STATUS = 'U' AND INV_TYPE = 'I' AND @user = 'ALEACH'
END