DECLARE 
@tax NVARCHAR(30),
@taxrate NVARCHAR(30),
@exch NVARCHAR(30);

SELECT 
@tax = COALESCE(IVL_TAX,'GST10'),
@exch = INV_EXCH
FROM R5INVOICELINES 
LEFT OUTER JOIN R5INVOICES ON IVL_INVOICE = INV_CODE
WHERE IVL_SQLIDENTITY = :rowid


SELECT 
@taxrate = CASE WHEN @tax in ('GST10','GST10CAP') THEN 0.1 ELSE 0 END

UPDATE R5INVOICELINES
SET IVL_TAX = 'GST10'
,IVL_EXCH = @exch
,IVL_TOTTAXAMOUNT = @taxrate * IVL_INVVALUE
WHERE IVL_SQLIDENTITY = :rowid
