UPDATE R5ORDERS
SET ORD_UDFCHAR01 =(
        SELECT COM_UDFCHAR01 -- Suppliers ABN
        FROM R5COMPANIES
        WHERE COM_CODE = ORD_SUPPLIER
    )
WHERE ORD_SQLIDENTITY = :rowid
    AND ORD_SUPPLIER IS NOT NULL
