UPDATE R5SESSIONS
    SET SES_REPORTLEVEL = 1
    FROM R5USERS
    LEFT OUTER JOIN R5SESSIONS ON SES_USER = USR_CODE AND USR_508 = '+' 
    WHERE USR_SQLIDENTITY = :rowid

UPDATE R5USERS 
    SET USR_508 = '-'
    WHERE USR_SQLIDENTITY = :rowid AND USR_508 = '+' 
