DECLARE
@EQROBJCODE NVARCHAR(30)
,@EQROBJORG NVARCHAR(30)
,@TYPE NVARCHAR(30)
,@EQRRANKINGCODE NVARCHAR(30)
,@EQRRANKINGORG NVARCHAR(30)
,@EQRRANKINGREVISION NVARCHAR(30)
,@SCORE NVARCHAR(30)
,@RRINDEX NVARCHAR(30)
,@MESSAGE NVARCHAR(30)
,@RECSDONE NVARCHAR(30)
,@RECSLOCKED NVARCHAR(30)
,@CHK NVARCHAR(30)
,@mess NVARCHAR(200);

SELECT
@EQROBJCODE = '000G1EW002B'
,@EQROBJORG = 'VDP'
,@TYPE = 'P'
,@EQRRANKINGCODE = 'WTS_CRITICALITY_2020_PARENT'
,@EQRRANKINGORG = 'VDP'
,@EQRRANKINGREVISION = '0'

  /* Do the actual calculation. */
  EXECUTE O7CALCOBJRRSCORE
    @EQROBJCODE
    ,@EQROBJORG
    ,@TYPE
    ,@EQRRANKINGCODE
    ,@EQRRANKINGORG
    ,@EQRRANKINGREVISION
    ,NULL
    ,@SCORE OUTPUT
    ,@RRINDEX OUTPUT
    ,@MESSAGE OUTPUT
    ,@RECSDONE OUTPUT
    ,@RECSLOCKED OUTPUT
    ,@CHK OUTPUT
