SELECT CRE_CREW, PER_DESC, EVT_CODE, EVT_DESC, OBJ_CODE, OBJ_DESC, ACT_ACT, TRD_DESC, ACT_NOTE, ACT_TASK+' :: '+TSK_DESC TASK, ACT_EST, BOO_DATE, SUM(BOO_HOURS) ACTUAL, ACT_EST - SUM(BOO_HOURS) HRS_UNDER
FROM R5CREWEMPLOYEES 
INNER JOIN R5PERSONNEL ON PER_CODE = CRE_PERSON
INNER JOIN R5BOOKEDHOURS ON BOO_PERSON = PER_CODE
INNER JOIN R5ACTIVITIES ON ACT_ACT = BOO_ACT AND ACT_EVENT = BOO_EVENT
INNER JOIN R5EVENTS ON EVT_CODE = ACT_EVENT
INNER JOIN R5OBJECTS ON OBJ_CODE = EVT_OBJECT AND OBJ_ORG = EVT_OBJECT_ORG
LEFT OUTER  JOIN R5TRADES ON TRD_CODE = ACT_TRADE
LEFT OUTER JOIN R5TASKS ON TSK_CODE = ACT_TASK
GROUP BY CRE_CREW, PER_DESC, EVT_CODE, EVT_DESC, OBJ_CODE, OBJ_DESC, ACT_ACT, TRD_DESC, ACT_NOTE, ACT_TASK, TSK_DESC TASK, ACT_EST, BOO_DATE